name: Create Chunk Statistics
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Create injected
        env:
          MAKE_VERSION: ${{ github.event.inputs.version }}
        run: |
          chmod +x gradlew
          ./gradlew runStatisticsNotRun

      - name: Upload injected
        uses: actions/upload-artifact@v4
        with:
          name: statistics-maker-${{ github.event.inputs.version }}
          path: |
            run/remapped/*.jar